In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8036, 3540, 9875, 6699],
 [8036, 3540, 9875, 5182],
 [8036, 5760, 9875, 2777],
 [1210, 2348, 8810, 4070, 2089],
 [1210, 2348, 8810, 4070, 2557],
 [7066, 8036, 165, 9875, 3836],
 [6274, 5674, 158, 4070]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8036 3540 9875 6699]
 [   0    0    0    0 8036 3540 9875 5182]
 [   0    0    0    0 8036 5760 9875 2777]
 [   0    0    0 1210 2348 8810 4070 2089]
 [   0    0    0 1210 2348 8810 4070 2557]
 [   0    0    0 7066 8036  165 9875 3836]
 [   0    0    0    0 6274 5674  158 4070]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step


array([[[-2.31791977e-02,  4.13086526e-02,  1.68596618e-02,
         -1.47506706e-02, -4.99619022e-02, -2.90682558e-02,
          4.50567044e-02,  3.60668190e-02, -8.90285894e-03,
          3.05434577e-02],
        [-2.31791977e-02,  4.13086526e-02,  1.68596618e-02,
         -1.47506706e-02, -4.99619022e-02, -2.90682558e-02,
          4.50567044e-02,  3.60668190e-02, -8.90285894e-03,
          3.05434577e-02],
        [-2.31791977e-02,  4.13086526e-02,  1.68596618e-02,
         -1.47506706e-02, -4.99619022e-02, -2.90682558e-02,
          4.50567044e-02,  3.60668190e-02, -8.90285894e-03,
          3.05434577e-02],
        [-2.31791977e-02,  4.13086526e-02,  1.68596618e-02,
         -1.47506706e-02, -4.99619022e-02, -2.90682558e-02,
          4.50567044e-02,  3.60668190e-02, -8.90285894e-03,
          3.05434577e-02],
        [ 4.66538593e-03, -4.19062264e-02, -2.33661663e-02,
          3.49520333e-02,  5.71974367e-03, -8.08424875e-03,
          9.26326960e-04, -4.94080894e-02,  2.079394

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8036, 3540, 9875, 6699], dtype=int32)

In [16]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[[-0.0231792 ,  0.04130865,  0.01685966, -0.01475067,
         -0.0499619 , -0.02906826,  0.0450567 ,  0.03606682,
         -0.00890286,  0.03054346],
        [-0.0231792 ,  0.04130865,  0.01685966, -0.01475067,
         -0.0499619 , -0.02906826,  0.0450567 ,  0.03606682,
         -0.00890286,  0.03054346],
        [-0.0231792 ,  0.04130865,  0.01685966, -0.01475067,
         -0.0499619 , -0.02906826,  0.0450567 ,  0.03606682,
         -0.00890286,  0.03054346],
        [-0.0231792 ,  0.04130865,  0.01685966, -0.01475067,
         -0.0499619 , -0.02906826,  0.0450567 ,  0.03606682,
         -0.00890286,  0.03054346],
        [ 0.00466539, -0.04190623, -0.02336617,  0.03495203,
          0.00571974, -0.00808425,  0.00092633, -0.04940809,
          0.02079395, -0.00204536],
        [-0.02744254, -0.03595507, -0.04451933,  0.00486334,
         -0.02098079,  0.03448125, -0.03814905, -0.03163334,
         -0.03588499,  0.03669871],
        [-0.03913219, -0.01551174, -0.03312571,  0.0